analytics: {}
color:
  brandColors:
    - '#20201b'
    - '#ce9d3e'
    - '#d7c88c'
    - '#b06f24'
    - '#948b7f'
  brandStrength: 0
  lightness: 0.0625
  rhythmicContrast: 1
  saturation: 0.125
cta: {}
layout_spectrum: 0.754505
name: steverosenMUSIC
opengraph: {}
purpose: []
typography_spectrum: 0.61038
