analytics: {}
color:
  brandColors:
    - '#D8E0E8'
    - '#285860'
    - '#6098A0'
    - '#78B8C8'
    - '#B0D0E0'
  brandStrength: 0
  lightness: 0.0625
  rhythmicContrast: 1
  saturation: 0.125
cta: {}
layout_spectrum: 0.754505
name: steverosenMUSIC
opengraph: {}
purpose: []
typography_spectrum: 0.61038
