name: steverosenMUSIC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20201b'
    - '#ce9d3e'
    - '#d7c88c'
    - '#b06f24'
    - '#948b7f'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
