analytics: {}
color:
  brandColors:
    - '#D8E0E8'
    - '#285860'
    - '#6098A0'
    - '#78B8C8'
    - '#B0D0E0'
  brandStrength: 1
  lightness: 0.497748
  rhythmicContrast: 0.488739
  saturation: 0.997748
cta: {}
layout_spectrum: 0.754505
name: steverosenMUSIC
opengraph: {}
purpose: []
typography_spectrum: 0.61038
