name: steverosenMUSIC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#654d5d'
    - '#201825'
    - '#bd6725'
    - '#d8cc63'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
