name: steverosenMUSIC
favicon: null
layout_spectrum: 0.40795501903630793
typography_spectrum: 0.4328914158977568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8770917493384331
  lightness: 0.059976937947794795
  saturation: 0.4470571738202125
  rhythmicContrast: 0.36410167603753507
purpose: []
